## Funciones Universales

pg 50

Las operaciones en Numpy pueden ser muy rápidas si evitamos los bucles y usamos operaciones vectorizadas con las "Universal functions (ufuncs)"

In [1]:
import numpy as np

In [2]:
np.random.seed(0)

In [7]:
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

In [8]:
values = np.random.randint(1, 10, size=5)

In [9]:
values

array([4, 6, 3, 5, 8])

In [10]:
compute_reciprocals(values)

array([0.25      , 0.16666667, 0.33333333, 0.2       , 0.125     ])

In [11]:
big_array = np.random.randint(1, 100, size=1000000)

In [12]:
%timeit compute_reciprocals(big_array)

1.67 s ± 29.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


## UFuncs

In [13]:
%timeit (1.0/big_array)

1.13 ms ± 14.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


Compara el valor de lo que ser tarda haciendolo con un loop o usando la operación vectorizada...

Los arrays pueden ser multidimensionales

In [15]:
x = np.arange(9).reshape(3,3)

In [16]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
x2 = x ** 2

In [18]:
x2

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

Hay de dos tipos:
* Unitarias. Con un solo input.
* Binarias. Con dos inputs.
    
Todos los operadores aritmeticos de Python se pueden usar.
Estas operaciones son wrappers sobre funcones especificas de Numpy.
Por ejemplo "+" es np.add()  
**Mirar la tabla de la página 53**

In [2]:
# Valor absoluto
x = np.array([-2, -1, 0, 1])

In [3]:
abs(x)

array([2, 1, 0, 1])

In [4]:
# Trigonometricas
theta = np.linspace(0, np.pi, 3)

In [10]:
theta

array([0.        , 1.57079633, 3.14159265])

In [6]:
np.sin(theta)

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

In [7]:
np.cos(theta)

array([ 1.000000e+00,  6.123234e-17, -1.000000e+00])

In [8]:
np.tan(theta)

array([ 0.00000000e+00,  1.63312394e+16, -1.22464680e-16])

In [12]:
x = [-1, 0, 1]

In [13]:
np.arcsin(x)

array([-1.57079633,  0.        ,  1.57079633])

In [14]:
np.arccos(x)

array([3.14159265, 1.57079633, 0.        ])

In [15]:
np.arctan(x)

array([-0.78539816,  0.        ,  0.78539816])

In [17]:
# Exponenciales y logaritmicas 
x = [1, 2, 3]

In [18]:
np.exp(x)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [19]:
np.exp2(x)

array([2., 4., 8.])

In [20]:
np.power(3, x)

array([ 3,  9, 27])

In [21]:
np.log(x)

array([0.        , 0.69314718, 1.09861229])

In [22]:
np.log2(x)

array([0.       , 1.       , 1.5849625])

In [23]:
np.log10(x)

array([0.        , 0.30103   , 0.47712125])

In [24]:
# Más ufuncs especializadas con Scipy "scipy.special"

### Funciones avanzadas de Ufunc

In [25]:
# Especificar el output
x = np.arange(5)
y = np.empty(5)

In [26]:
np.multiply(x, 10, out=y)

array([ 0., 10., 20., 30., 40.])

In [27]:
y

array([ 0., 10., 20., 30., 40.])

In [34]:
# Agregados
x = np.arange(1, 6)

In [31]:
np.add.reduce(x) # Suma todo el array

15

In [36]:
np.multiply.reduce(x)

120

In [37]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120])

Otra funcionalidad extremadamente importante de las ufuncs es poder operar arrays de diferentes dimensiones y tamaños. A esto se le llama **broadcasting**

### Agregaciones