## Funciones Universales

pg 50

Las operaciones en Numpy pueden ser muy rápidas si evitamos los bucles y usamos operaciones vectorizadas con las "Universal functions (ufuncs)"

In [1]:
import numpy as np

In [2]:
np.random.seed(0)

In [7]:
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

In [8]:
values = np.random.randint(1, 10, size=5)

In [9]:
values

array([4, 6, 3, 5, 8])

In [10]:
compute_reciprocals(values)

array([0.25      , 0.16666667, 0.33333333, 0.2       , 0.125     ])

In [11]:
big_array = np.random.randint(1, 100, size=1000000)

In [12]:
%timeit compute_reciprocals(big_array)

1.67 s ± 29.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


## UFuncs

In [13]:
%timeit (1.0/big_array)

1.13 ms ± 14.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


Compara el valor de lo que ser tarda haciendolo con un loop o usando la operación vectorizada...

Los arrays pueden ser multidimensionales

In [15]:
x = np.arange(9).reshape(3,3)

In [16]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
x2 = x ** 2

In [18]:
x2

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

Hay de dos tipos:
* Unitarias. Con un solo input.
* Binarias. Con dos inputs.
    
Todos los operadores aritmeticos de Python se pueden usar.
Estas operaciones son wrappers sobre funcones especificas de Numpy.
Por ejemplo "+" es np.add()  
**Mirar la tabla de la página 53**

### Valor absoluto