# Aggregations: Min, Max...

pg 58

In [1]:
import numpy as np

### Suma

In [3]:
L = np.random.random(100)

In [4]:
sum(L)

47.12106722532835

In [5]:
np.sum(L)

47.121067225328346

Aunque la función es muy similar a la estandar de Python es preferible usar la de Numpy ya que es mucho más rápida.
Hay que tener cuidado se se incluyen parámetros opcionales ya que ahí si cambia el comportamiento.

### Minimo y Maximo

In [7]:
np.min(L)

0.021773484512610075

In [8]:
np.max(L)

0.9983688377706119

### Agregados multidimensionales

In [10]:
M = np.random.random((3,4))

In [11]:
M

array([[0.39998466, 0.8772017 , 0.78837732, 0.28612381],
       [0.10541427, 0.62726949, 0.43856596, 0.37840427],
       [0.22391772, 0.70865784, 0.62896453, 0.77664348]])

In [13]:
# Minimo de cada columna
M.min(axis=0)

array([0.10541427, 0.62726949, 0.43856596, 0.28612381])

In [14]:
# Maximo de cada fila.
M.max(axis=1)

array([0.8772017 , 0.62726949, 0.77664348])

### Para ver todas las funciones y su versión NaN safe consultar tabla pg 61

### Ejemplo de uso en pg 61 con Pandas y Matplotlib