# Broadcasting

pg 63

Es un set de reglas para aplicar ufuncs en arrays de diferentes tamaños.

In [1]:
import numpy as np

In [2]:
a = np.array([0, 1, 2])

In [3]:
a + 5 

array([5, 6, 7])

In [4]:
M = np.ones((3, 3))

In [5]:
M + a

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [8]:
b = np.arange(3)[: ,np.newaxis]

In [9]:
b

array([[0],
       [1],
       [2]])

In [10]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

La figura 2.4 en pg 65 tiene una buena representación gráfica.

### Las reglas

Sigue unas reglas estrictas:
1. Si ambas difieren en dimensiones la mas pequeña se iguala a la mayor.
2. Si no coinciden en ninguna dimension la que tenga 1 dimension se iguala a la mayor.
3. Si no coinciden y no hay ninguna con 1 dimension se devuelve un error.

### Ejemplos de uso

In [11]:
# Centrar un array

In [12]:
# Tenemos un array de 10 observaciones con 3 campos cada observación.
X = np.random.random((10, 3))

In [13]:
X

array([[0.85421932, 0.76236454, 0.42119922],
       [0.09648863, 0.94172376, 0.92141269],
       [0.32428239, 0.18911532, 0.08940493],
       [0.93033024, 0.72448723, 0.72768753],
       [0.46273568, 0.10768199, 0.61137755],
       [0.12186368, 0.77826257, 0.96475673],
       [0.55679422, 0.99765098, 0.25027754],
       [0.15045268, 0.83864023, 0.13303051],
       [0.37798873, 0.45587168, 0.12759358],
       [0.18229647, 0.31079543, 0.97338919]])

In [23]:
# Podemos obtener la media de cada campo viendo la media de la columna.
Xmean = X.mean(axis = 0)

In [24]:
Xmean

array([0.4057452 , 0.61065937, 0.52201295])

In [25]:
# Para centrar el array sustraemos a cada valor su media.
Xcentered = X - Xmean

In [26]:
# Esta es la operación de broadcasting
Xcentered

array([[ 0.44847411,  0.15170516, -0.10081373],
       [-0.30925657,  0.33106439,  0.39939975],
       [-0.08146282, -0.42154406, -0.43260801],
       [ 0.52458504,  0.11382785,  0.20567458],
       [ 0.05699048, -0.50297738,  0.0893646 ],
       [-0.28388153,  0.1676032 ,  0.44274378],
       [ 0.15104902,  0.38699161, -0.27173541],
       [-0.25529252,  0.22798086, -0.38898244],
       [-0.02775647, -0.15478769, -0.39441937],
       [-0.22344874, -0.29986394,  0.45137624]])

In [27]:
# Para comprobar que está centrada el valor de la media ahora debe ser casi 0
Xcentered.mean(axis=0)

array([-5.55111512e-18,  6.66133815e-17,  7.77156117e-17])