# Comparisons, Masks, and Boolean Logic

pg 70

Las comparaciones, mascaras y lógica booleanas son muy utiles para realizar muchas operaciones.  
Contar los valores mayores a un valor dado, quitar los outliers.  
EJ lluvia: Cuantos dias de lluvia hubo, cual es la media de estos, en cuantos se supero cierta cantidad...

Numpy tiene operadores de comparación al igual que aritmeticos (<, >, =) Estos operadores siempre devuelven una array de **booleanos**

In [2]:
import numpy as np

In [3]:
x = np.array([1,2,3,4,5])

In [4]:
x < 3

array([ True,  True, False, False, False])

Al igual que con los aritmeticos, internamente np tiene su función EJ: "<" es np.less (pg 72)

### Trabajando con Booleans 

In [11]:
x = np.array([[5, 0, 3, 3],
              [7, 9, 3, 5],
              [2, 4, 7, 6]])

In [12]:
# Contando entradas
np.count_nonzero(x < 6)

8

In [14]:
# Mejor son sum
np.sum(x < 6)

8

In [13]:
# Alguno mayor o menor a valor
np.any(x > 8)

True

In [17]:
# Todos
np.all(x == 6)

False

### Los operadores lógicos son: & | ^ ~

### Mask

In [18]:
x[x < 5]

array([0, 3, 3, 3, 2, 4])

In [20]:
condicion = x > 8

In [21]:
x[condicion]

array([9])