# Fancy index
pg78

Es otro modo de indexing de arrays. Pasamos **arrays de indices** en lugar de escalares.

In [1]:
import numpy as np

In [5]:
rand = np.random.RandomState(42)
x = np.random.randint(100, size=10)

In [7]:
x

array([79, 29, 90, 72, 80, 86, 36, 57, 53, 94])

In [8]:
# Accedemos a 3 elementos diferentes
[x[3], x[7], x[2]]

[72, 57, 90]

In [10]:
ind = [3, 7, 2]
x[ind]

array([72, 57, 90])

In [11]:
# con Fancy podemos crear ya el array que queramos
ind = np.array([[3, 7],
                [4, 5]])

In [12]:
x[ind]

array([[72, 57],
       [80, 86]])

Se pude combinar cualquier tipo de indexing, fancy, simple, slicing.

Tambien podemos modificar los valores

In [14]:
x[ind] = 99

In [15]:
x

array([79, 29, 90, 99, 99, 99, 36, 99, 53, 94])