# Ordenando arrays
pg 85

Algoritmo clásico de ordenación

In [2]:
import numpy as np

In [42]:
def selection_sort(x):
    for i in range(len(x)):
        swap = i + np.argmin(x[i:])
        print(x[i], x[swap])
        (x[i], x[swap]) = (x[swap], x[i])
        print(x)
    return x

In [46]:
x = np.array([2, 1, 4, 3, 5])

In [47]:
selection_sort(x)

2 1
[1 2 4 3 5]
2 2
[1 2 4 3 5]
4 3
[1 2 3 4 5]
4 4
[1 2 3 4 5]
5 5
[1 2 3 4 5]


array([1, 2, 3, 4, 5])

### Fast sorting

Python tiene un método pero el de numpy es mucho más eficiente.

In [48]:
np.sort(x)

array([1, 2, 3, 4, 5])

In [50]:
x.sort()
print(x)

[1 2 3 4 5]


In [53]:
# Tambien podemos obtener los indeces ordenados
x = np.array([2, 1, 4, 3, 5])
i = np.argsort(x)

In [54]:
i

array([1, 0, 3, 2, 4])

In [55]:
# y crear el array ordenado con fancy indexing

In [56]:
x[i]

array([1, 2, 3, 4, 5])

In [57]:
# Se puede añadir el eje que quermos ordenar con axis = 0 para columnas y 1 para filas

### Partial sorting

Si no se desea ordenar el array entero podemos elegir cuantos elemntos a ordenar. Indica los K más pequeños en un orden aleatorio.

In [58]:
x = np.array([7,2,3,1,6,5,4])

In [59]:
np.partition(x, 3)

array([2, 1, 3, 4, 6, 5, 7])

In [60]:
# También se puede especificar el eje.

### Hay un ejemplo de como KNN funciona internamente en la pg 89