## Atributos

In [1]:
import numpy as np

In [2]:
np.random.seed(0)

In [8]:
np_array = np.random.randint(10, size=(3, 4, 5))

In [9]:
np_array

array([[[4, 3, 4, 4, 8],
        [4, 3, 7, 5, 5],
        [0, 1, 5, 9, 3],
        [0, 5, 0, 1, 2]],

       [[4, 2, 0, 3, 2],
        [0, 7, 5, 9, 0],
        [2, 7, 2, 9, 2],
        [3, 3, 2, 3, 4]],

       [[1, 2, 9, 1, 4],
        [6, 8, 2, 3, 0],
        [0, 6, 0, 6, 3],
        [3, 8, 8, 8, 2]]])

In [10]:
print("ndim: ", np_array.ndim)
print("shape: ", np_array.shape)
print("size: ", np_array.size)

ndim:  3
shape:  (3, 4, 5)
size:  60


In [14]:
print("dtype: ", np_array.dtype)
print("itemsize: ", np_array.itemsize, "bytes")
print("nbytes: ", np_array.nbytes)

dtype:  int64
itemsize:  8 bytes
nbytes:  480


## Accediendo a elementos

In [5]:
x = np.random.randint(0, 12, (3, 4))

In [6]:
x

array([[ 5,  0,  3, 11],
       [ 3,  7,  9,  3],
       [ 5,  2,  4,  7]])

In [9]:
x[:2, :3] # two rows 3 columns

array([[5, 0, 3],
       [3, 7, 9]])

In [11]:
x[:3, ::2] # All rows every other column

array([[5, 3],
       [3, 9],
       [5, 4]])

In [12]:
x[::-1, ::-1] # reverse all

array([[ 7,  4,  2,  5],
       [ 3,  9,  7,  3],
       [11,  3,  0,  5]])

## Copias

Algo muy importante a tener en cuenta es que las partes que obtenemos son vistas, no copias.
Por lo tanto si modificamos la vista estamos modificando el original.
Si no queremos que esto ocurra hay que hacer copias. Esto muy útil ya que podemos partir un array muy grande. Trabajar con la parte que deseamos sin cargar el resto y guardar el resultado.

In [13]:
# Si no queremos modificar el original

In [23]:
x2 = np.random.randint(0, 12, (3, 4))

In [24]:
x2

array([[8, 9, 4, 3],
       [0, 3, 5, 0],
       [2, 3, 8, 1]])

In [25]:
x2_no_copy = x2[:2, :2]

In [26]:
x2_no_copy[0 , 0] = 66

In [27]:
x2

array([[66,  9,  4,  3],
       [ 0,  3,  5,  0],
       [ 2,  3,  8,  1]])

In [28]:
x2_copy = x2[:2, :2].copy()

In [29]:
x2_copy

array([[66,  9],
       [ 0,  3]])

In [30]:
x2_copy[0 , 0] = 99

In [31]:
x2_copy

array([[99,  9],
       [ 0,  3]])

In [33]:
x2

array([[66,  9,  4,  3],
       [ 0,  3,  5,  0],
       [ 2,  3,  8,  1]])

## Redimensionar

A tener en cuenta: El tamaño de la inicial debe ser igual al de la redimensionada.

In [35]:
grid = np.arange(1,10).reshape(3,3)

In [36]:
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
# Convertir una dimensión en matriz.

In [38]:
arr = np.array([1, 2, 3])

In [39]:
arr

array([1, 2, 3])

In [40]:
arr.reshape(1,3)

array([[1, 2, 3]])

In [42]:
arr[np.newaxis, :]

array([[1, 2, 3]])

In [43]:
arr.reshape(3,1)

array([[1],
       [2],
       [3]])

In [44]:
arr[:, np.newaxis]

array([[1],
       [2],
       [3]])

## Concatenar y partir

In [46]:
grid = np.arange(1,7).reshape(2,3)

In [53]:
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
np.concatenate([grid, grid], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [50]:
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [51]:
x = np.array([99,99,99])

In [54]:
np.vstack([x, grid])

array([[99, 99, 99],
       [ 1,  2,  3],
       [ 4,  5,  6]])

In [56]:
y = np.array([[99],
              [99]])

In [57]:
np.hstack([y, grid])

array([[99,  1,  2,  3],
       [99,  4,  5,  6]])

In [58]:
# dstack para el tercer eje

In [59]:
x = [1, 2, 3, 99, 99, 3, 2, 1]

In [60]:
x1, x2, x3 = np.split(x, [3, 5]) # indicamos el indice, parte en el 3 y el 5

In [61]:
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [62]:
grid2 = np.arange(16).reshape(4,4)

In [63]:
grid2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [67]:
upper, lower = np.vsplit(grid2, [2])

In [68]:
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [69]:
right, left = np.hsplit(grid2, [2])

In [70]:
print(right)
print(left)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [71]:
# dsplit para el tercer eje