## Creando Arrays desde listas Python

pg 39

In [2]:
import numpy as np

In [3]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

Numpy, al contrario de Python, solo maneja un tipo en las arrays.

In [4]:
np.array([3.14, 4, 2])

array([3.14, 4.  , 2.  ])

Si queremos especificar el tipo se puede hacer con **dtype**

In [5]:
np.array([1,2,3,4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

Las arrays de NumPy pueden ser multi dimensionales

In [6]:
# Listas anidadas
np.array([range(i,i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

## Creando arrays desde cero

In [3]:
np.zeros(10, dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [4]:
np.ones((3,5), dtype='float')

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [5]:
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [6]:
# Entre 0 y 20 cada 2
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
# linear entre 0 y 10, 5 valores
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [10]:
# random de 3x3 (0-1)
np.random.random((3, 3))

array([[0.46691942, 0.08480065, 0.79759313],
       [0.62480236, 0.28677948, 0.49985261],
       [0.55202899, 0.62363738, 0.30785514]])

In [13]:
# random distribucion normal. de 0 a 10
np.random.normal(0, 10, (3, 3))

array([[  5.42451878,  15.52931089,   6.71615984],
       [-17.85253506,  -0.70490502,   8.516998  ],
       [  3.31295996, -13.75182268, -15.83365783]])

In [14]:
# identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
# crear una vacía con la dimensión deseada
np.empty(3)

array([1., 1., 1.])