## Creando Arrays desde listas Python

pg 39

In [2]:
import numpy as np

In [3]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

Numpy, al contrario de Python, solo maneja un tipo en las arrays.

In [4]:
np.array([3.14, 4, 2])

array([3.14, 4.  , 2.  ])

Si queremos especificar el tipo se puede hacer con **dtype**

In [5]:
np.array([1,2,3,4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

Las arrays de NumPy pueden ser multi dimensionales

In [6]:
# Listas anidadas
np.array([range(i,i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

## Creando arrays desde cero